application: californiaysa
version: 1
runtime: python
api_version: 1

handlers:
- url: /weekly_report
  script: weekly_report.py

- url: /final_report
  script: final_report.py

- url: /submit/.*
  script: submit.py

- url: /sql/.*
  script: sql_dump.py

- url: /
  static_dir: static